import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header/header";
import { Providers } from "./redux/providers";
import ThemeClient from "./components/theme-client";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ThemeClient />
            <div className="bg-white dark:bg-zinc-800">
              <div className="min-h-screen mx-auto px-3 sm:px-8 xl:px-32 lg:px-16">
                <Header />
                {children}
              </div>
            </div>
        </Providers>
      </body>
    </html>
  );
}
